version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bacongobbler/kubed-generator-sdk-go
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Test
          command: .circleci/test.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
